site_name: Made With ML
site_url: https://madewithml.com/
repo_url: https://github.com/mathijsvdv/Made-With-ML/
nav:
  - Home: index.md
  - madewithml:
    - data: src/madewithml/data.md
    - models: src/madewithml/models.md
    - train: src/madewithml/train.md
    - tune: src/madewithml/tune.md
    - evaluate: src/madewithml/evaluate.md
    - predict: src/madewithml/predict.md
    - serve: src/madewithml/serve.md
    - utils: src/madewithml/utils.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes
