name: workloads
on:
  workflow_dispatch:  # manual
  pull_request:
    branches:
    - main
permissions: write-all

jobs:
  workloads:
    runs-on: ubuntu-22.04
    steps:

      # Configure AWS credentials
      - name: Configure AWS credentials
      - run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Check that AWS credentials are set up correctly
      - name: Check AWS credentials
      - run: aws configure list

      # Set up dependencies
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install ray[default,air]==2.6.3 boto3==1.28.39 hydra-core==1.3.2

      # Set up Ray cluster
      - name: Set up Ray cluster
        run: |
          ray up cluster.yaml -y --no-restart
          ray dashboard cluster.yaml

      # Run workloads
      - name: Workloads
        run: |
          make workloads

      # Tear down Ray cluster
      - name: Tear down Ray cluster
        if: always()
        run: ray down cluster.yaml -y

      # Read results from S3
      - name: Read results from S3
        run: |
          mkdir results
          aws s3 cp s3://madewithml/${{ env.S3_BUCKET }}/results/ results/ --recursive
          python .github/workflows/json_to_md.py results/training_results.json results/training_results.md
          python .github/workflows/json_to_md.py results/evaluation_results.json results/evaluation_results.md

      # Comment results to PR
      - name: Comment training results on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: results/training_results.md
      - name: Comment evaluation results on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: results/evaluation_results.md
